[package]
name = "projet_hal"
version = "0.1.0"
edition = "2024"

[dependencies]
panic-halt = "0.2"  # Used to handle panic in no_std environments

[features]
default = ["atmega328p"]  # Specify your target chip here

[dependencies.avr-device]
version = "0.3"
optional = true
